server:
  port: 8080
spring:
  profiles:
    active: dev
  application:
    name: springfox-swagger
swagger:
  enable: false
  application-name: ${spring.application.name}
  application-version: 1.0
  application-description: springfox swagger 3.0整合Demo
  try-host: http://localhost:${server.port}
