debug: true
spring:
  data:
    mongodb:
      uri: mongodb://localhost:27017/ghdg
  datasource:
    password: root
    url: jdbc:mysql://localhost:3306/ghdg?useUnicode=true&characterEncoding=UTF-8&useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=GMT%2B8
    username: root
  jpa:
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    hibernate:
      ddl-auto: none
    show-sql: true
  sql:
    init:
      encoding: utf-8
